# Generated by Django 5.1.6 on 2025-02-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_options_alter_subcategory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "подкатегория",
                "verbose_name_plural": "подкатегории",
            },
        ),
    ]
