# Generated by Django 5.1.6 on 2025-02-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_subcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug_name",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug_name",
            field=models.SlugField(unique=True),
        ),
    ]
