# Generated by Django 5.1.6 on 2025-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_alter_category_slug_name_alter_subcategory_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug_name",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
