# Generated by Django 5.1.6 on 2025-02-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_category_slug_name_alter_subcategory_slug_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="slug_name",
            field=models.SlugField(
                blank=True,
                help_text="поле заполняется автоматически",
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "slug_name",
                    models.SlugField(
                        blank=True,
                        help_text="поле заполняется автоматически",
                        null=True,
                        unique=True,
                    ),
                ),
                ("image1", models.ImageField(upload_to="")),
                (
                    "image2",
                    models.ImageField(
                        height_field=200,
                        help_text="заполняется автоматически",
                        upload_to="",
                        width_field=200,
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        height_field=300,
                        help_text="заполняется автоматически",
                        upload_to="",
                        width_field=200,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
