# Generated by Django 5.1.6 on 2025-02-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_subcategory_slug_name_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image1",
            field=models.ImageField(upload_to="products/image1"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                height_field=200, upload_to="products/image2", width_field=200
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                height_field=300, upload_to="products/image3", width_field=200
            ),
        ),
    ]
