# Generated by Django 5.1.6 on 2025-02-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_image1_alter_product_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.ImageField(upload_to="products/image2"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.ImageField(upload_to="products/image3"),
        ),
    ]
