# Generated by Django 5.1.6 on 2025-02-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_category_image_alter_product_image1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image1",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image3",
        ),
    ]
