# Generated by Django 5.1.6 on 2025-02-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_rename_image1_product_image_remove_product_image2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="image1",
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
