# Generated by Django 5.1.6 on 2025-02-23 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_rename_image_product_image1_product_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="изображение"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="наименование"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug_name",
            field=models.SlugField(
                blank=True,
                help_text="поле заполняется автоматически",
                null=True,
                unique=True,
                verbose_name="slug-имя",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image1",
            field=models.ImageField(upload_to="", verbose_name="изображение 200*200"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="изображение 400*400"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="изображение 600*600"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="наименование"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug_name",
            field=models.SlugField(
                blank=True,
                help_text="поле заполняется автоматически",
                null=True,
                unique=True,
                verbose_name="slug-имя",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.subcategory",
                verbose_name="подкатегория",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="products.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="изображение"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="наименование"
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug_name",
            field=models.SlugField(
                blank=True,
                help_text="поле заполняется автоматически",
                null=True,
                unique=True,
                verbose_name="slug-имя",
            ),
        ),
    ]
