# Generated by Django 5.1.6 on 2025-02-23 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_alter_category_image_alter_category_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="количество товаров"
                    ),
                ),
                (
                    "total_price",
                    models.PositiveIntegerField(
                        default=0, verbose_name="сумма товаров в корзине"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="products",
                        to="products.product",
                        verbose_name="продукты",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "корзина",
                "verbose_name_plural": "корзины",
            },
        ),
    ]
