# Generated by Django 5.1.6 on 2025-02-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_basket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Basket",
        ),
    ]
